### ISSUE TITLE
auto close parenthesis plugins

### ISSUE THREAD

**Issue by nhooyr** [justinmk/config#2]
I noticed you created https://github.com/cohama/lexima.vim/issues/2

Do you just not use any plugin for auto closing parenthesis because they all break undo? Is there some alternative approach or do you just do everything manually?

**Comment by nhooyr** [comment]
nvm, looks like it was fixed in https://github.com/Raimondi/delimitMate/pull/227

**Comment by justinmk** [comment]
@nhooyr I'm just using some basic mappings at the moment, plus endwise.vim:

https://github.com/justinmk/config/blob/11c19bd100422a8333164185903f55d60a90efc4/.config/nvim/init.vim#L134-L143                           

I haven't got back on the delimitmate bandwagon yet because AFAIK it still doesn't support dot-repeat (as lexima does). So both plugins are still deficient.

**Comment by nhooyr** [comment]
Did https://github.com/Raimondi/delimitMate/pull/227 not add support for that?

**Comment by justinmk** [comment]
Oops, maybe it did. I didn't try it since then.

**Comment by nhooyr** [comment]
I tested and confirmed, looks good.

**Comment by nhooyr** [comment]
jk, problems like https://github.com/Raimondi/delimitMate/issues/214 still don't make it a perfect solution. :(

**Comment by nhooyr** [comment]
jk, the problem isn't actually there. You just have to press `>` after the closing tag (it's already there because of delimitMate which is why the person in the issue was confused). I just disable the expansion of `<` in html/eex files from delimitMate and use https://github.com/alvan/vim-closetag.
